openapi: 3.0.0
info:
  title: Task Management API
  description: API for managing tasks
  version: 1.0.0
paths:
  /tasks:
    get:
      summary: Get all tasks
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                - id: 1
                  title: "Complete tutorial"
                  completed: false
                - id: 2
                  title: "Write blog post"
                  completed: true
    post:
      summary: Create a new task
      requestBody:
        description: Task data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "Review pull requests"
                completed:
                  type: boolean
                  example: false
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              example:
                id: 3
                title: "Review pull requests"
                completed: false
